# Generated by Django 4.2.3 on 2023-08-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_projectdetail_alter_todolist_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoList',
        ),
        migrations.RenameField(
            model_name='projectdetail',
            old_name='group_no',
            new_name='gno',
        ),
        migrations.RenameField(
            model_name='projectdetail',
            old_name='project_detail',
            new_name='pdetail',
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='roll',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
