# Generated by Django 4.2.3 on 2023-08-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_todolist_rename_group_no_projectdetail_gno_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectdetail',
            table='project details',
        ),
    ]
